# PostgreSQL Supabase

spring.datasource.url=jdbc:postgresql://aws-1-us-east-1.pooler.supabase.com:5432/postgres

spring.datasource.username=postgres.diuolveckejbuibdbcjb

spring.datasource.password=helpPsi052026@!

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# porta da API
server.port=8081

# OpenCage
geocoding.opencage.api.key=e7aec811512b41bcaa73398a6891b52b